# Site settings
title: Pollyanna Souza
description: não há considerações gerais a fazer, está tudo aí
email: polle626@gmail.com
categories_pretty:
  a-indissociabilidade-entre-o-aprendizado-e-a-vida: A Indisssociabilidade entre o aprendizado e a vida
  doula: Doula
  o-renascimento-do-alexander: O Renascimento do Alexander
  blog: Lua ignorada

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
permalink: /:categories/:title
markdown: redcarpet
redcarpet:
  extensions:
    - :fenced_code_blocks
    - :superscript
    - :hard_wrap
    - :tables

# Development
host: 0.0.0.0
